### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Bookcliff** [Bookcliff/learning#1]
# Learning
## Learn core frontend concepts
- [x] learn everything up to react from https://roadmap.sh/frontend
- [x] Learn [react basics](https://beta.reactjs.org/learn) 
- [x] #7
- [x] #8
- [x] #9
- [x] #10
- [x] #4
- [x] #5
- [x] #6
- [x] Learn about how [promises](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) (always hard for beginners!) 
- [x] Read through all of [antd design patterns](https://ant.design/docs/spec/introduce) (this should be done after a building a website, refactoring it to follow all of the guidelines) 
- [ ] Revisit https://beta.reactjs.org/learn after doing a few projects and re-read and think about how to refactor my projects
- [x] Read [Javascript primer](https://eloquentjavascript.net/)
- [x] Read [TypeScript handbook](https://www.typescriptlang.org/docs/handbook/intro.html)

Avoid:
* Redux
* Anything using classes (likely outdated) 
* Callbacks for async code 

## Increase knowledge of Ethereum and DeFi
- [x] https://github.com/porter-finance/handbook/blob/main/company/engineering/onboarding.md
- [x]  Setup metamask wallet 
- [x] Setup bookcliff ENS
- [x] [DeFi llama TVL submission](https://defillama.com/protocol/arbor-finance)
- [x] Get testnet eth
- [ ] Interact with some DeFi protocols https://app.rabbithole.gg/skills (do things on here that are interesting and have testnets) 
- [ ] Run a testnet rocketpool node https://docs.rocketpool.net/guides/
- [ ] #11

## Backend 
This learning will be a bit less than the other areas. 
* [x] Learn about [vercel serverless functions](https://vercel.com/docs/concepts/functions/serverless-functions)
* [x] Create a telegram bot
* [x] Wedding website database/api
* [x] Learn SQL (work with Dune Analytics using SQL to interact with Avalanche's c-chain)
* [x] Work with python (https://github.com/alwaysbegrowing/conv-bonds-pricing) 

## Complete data science course
- [x] Lesson 1
- [x] Lesson 2

# Projects
- [x] Wedding website
- [x] #3
- [x] Telegram bot (sends parents weekly meeting info)
- [x] #13
- [ ] Build autogenerated Art NFT for porter or ABG
- [x] ABG components
- [x] Deephire help desk (DONE!!!! https://help.deephire.com) 
- [ ] #14
- [x] [Events page](https://github.com/alwaysbegrowing/events)
- [x] Deephire recruiter bugs
- [x] [Twitter api project](https://github.com/Bookcliff/tweet-api-likes)
- [x] [Coin-gecko Google Sheets API project](https://github.com/Bookcliff/leads-marketInfo)
- [x] [Call Option Pricing application](https://github.com/alwaysbegrowing/conv-bonds-pricing)

# Commitment 
* 40 focus mates per week 

# Schedule 
[Here's](https://github.com/mermaid-js/mermaid/blob/develop/docs/gantt.md) how you can make these charts. You may also want to consider using [projects](https://docs.github.com/en/issues/trying-out-the-new-projects-experience/about-projects) or [milestones](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-milestones) to manage this. 
```mermaid
gantt
    title Week 1
    dateFormat  YYYY-MM-DD

axisFormat %b-%d

    section Frontend
    Goals?          :active, a1, 2022-05-09, 5d


 ```

**Comment by RusseII** [comment]
# DeFi
- [ ] https://github.com/porter-finance/handbook/blob/main/company/engineering/onboarding.md
- [ ]  Setup metamask wallet, get testnet eth, interact with some DeFi protocols https://app.rabbithole.gg/skills (do things on here that are interesting and have testnets) 
- [ ]
