### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by Bookcliff** [Bookcliff/learning#15]
Week of May 23:

Monday, May 23: 
- [x] read about .gitignore
- [x] set up a discord bot (read a lot of the discord.js docs)
- [x] wrote out the flow for connecting the plugin, bot, and server (vercel - server less)
- [x] read about server less fxs
- [x] fixed deep hire issues
- [x] learned about node.js, package managers, and npm

Tuesday, May 24:
- [x] learned more about npm (e.g scripts)
- [x] reviewed discord.js and discord-interactions documentation
- [x] reviewed discord bots GitHub
- [x] fixed deep hire issue
- [x] started coding bot :)

Wednesday, May 25:

- [x] discord bot
- [x] reviewed GitHub repos for similar projects
- [x] lots of trial and error

Thursday, May 26:

- [x] kept working on bot
- [x] learned about web hooks
- [x] read about tokens 
- [x] read about APIs

Friday, May 27:

- [x] remade bot from scratch (new repo, used discord.js instead of discord-interactions)
- [x] got bot to work!
- [x] read MDN docs on promises

**Comment by Bookcliff** [comment]
Week of May 29

Sunday, May 29:
- [x] [read vercel docs](https://vercel.com/docs?redirected=1) & https://vercel.com/docs/runtimes#official-runtimes/node-js/node-js-request-and-response-objects
- [x] [stack overflow “how to ask a question”](https://stackoverflow.com/help/how-to-ask) & https://codeblog.jonskeet.uk/2010/08/29/writing-the-perfect-question/

Monday, May 30:

- [x] watched Russell’s video on how to set up a project
- [x] started simple Telegram bot to send parents weekly Google Meet link

Tuesday, May 31:

- [x] finished Telegram bot
- [x] set up test MetaMask account, read docs, participated in Porter practice auction for Ribbon

Wednesday, June 01:

- [x] learn about client-server model
- [x] learn about asynchronous functions and promises

Thursday, June 02:

- [x] read next.js docs, discord dev docs, discord.js docs & write out flow of bot (like a recipe)
- [x] work on discord gm bot

**Comment by Bookcliff** [comment]
Week of June 19:

Sunday, June 19:

- [x] Worked on landing page for wedding website (fixed styling, added button to home page, worked on border images)

Monday, June 20

- [x] Data science course (completed 1 module)

Tuesday, June 21

- [x] Data science course (completed 2 modules)
- [x] Worked on Deephire menu account tab issue

Wednesday, June 22

- [x] Data science course (completed 1 module)
- [x] Fixed DeepHire menu account tab issue, updated PR request
- [x] Started working on DeepHire candidate hiding/unhiding issue

Thursday, June 23

- [x] Fix wedding website border image
- [x] Pick font
- [x] Start on RSVP page (begin building database)

Friday, June 24

- [x] Work on RSVP page
- [x] Style RSVP page

**Comment by Bookcliff** [comment]
Monday, June 27

- [x] data science course (2 modules completed)
- [x] Deephire unarchive API issue (met with Russell for 2 hours and discussed the database, backend, and integration - still need to meet again to finish)

Tuesday June 28

- [x] learned about databases, MongoDB, and JSON
- [x] built the wedding website database in MongoDB

Thursday June 30

- [x] Build API skeleton
- [x] Read about APIs, MongoDB, and [protocol stacks](https://web.stanford.edu/class/msande91si/www-spr04/readings/week1/InternetWhitepaper.htm)

Friday July 01
- [x] Work on API
- [x] RSVP page styling

**Comment by Bookcliff** [comment]
Monday July 04

- [x] Finish building API backend and database
- [x] Test API
- [x] RSVP page styling

Tuesday July 05

- [x] Front end API
- [x] Familiarize self with fokus repo and project

Wednesday July 06

- [x] Finish RSVP front end of API
- [x] Re-read [React docs](https://reactjs.org/docs/)

Thursday July 06

- [x] RSVP Chipotle Order Form

Friday July 07

- [x] RSVP Chipotle Drawer
- [x] RSVP Chipotle API
- [x] Read Ant Design Docs

**Comment by Bookcliff** [comment]
Monday July 11

- [x] Data science course (3 modules)

Tuesday July 12

- [x] Discord GM bot - read discord developer & discord.js docs, watched YouTube videos

Wednesday July 13

- [x] Discord GM bot
- [x] read https://eloquentjavascript.net/ (3 chapters)

Thursday July 14

- [x] Write out GM Bot vision
- [x] Research webhooks w/discord
- [x] Tested discord webhook using postman
- [x] read https://eloquentjavascript.net/ (2 chapters)


Friday July 15

- [ ] GM Webhook 
- [ ] read https://eloquentjavascript.net

**Comment by Bookcliff** [comment]
Week of July 17 (on vacation): 

- [x] Read about discord webhooks, worked on identifying the process for creating, calling, and deleting webhooks for discord
- [x] Cleaned code for wedding website
- [x] Forked happy birthday repo and modified it (hosted through vercel)
- [x] Read https://eloquentjavascript.net/ (3 chapters)

**Comment by Bookcliff** [comment]
## Week of July 24:

### Goal: Six focused hours per day minimum

Monday, July 25

- [x] Data science course (6 modules completed)

Tuesday, July 26

- [x] GM Webhook
- [ ] [Read]( https://eloquentjavascript.net/ )

Wednesday, July 27

- [x] Russell Events Page (https://github.com/RusseII/events/issues/2)
- [ ] [Read]( https://eloquentjavascript.net/ )

Thursday, July 28

- [x] Watched Russell building events page videos ([part 1](https://video.russell.work/kW6pz7); [part 2](https://video.russell.work/WnLbwD); [part 3](https://video.russell.work/3RlwWr); [part 4](https://video.russell.work/On3PlV); [part 5](https://video.russell.work/4EsEYn))
- [x] Russell Events Page (https://github.com/RusseII/events/issues/2) - Fixed styling and sorting function
- [x] [Read]( https://eloquentjavascript.net/ ) (Chapter 10)

Friday, July 28

- [x] Russell events page - Added loading screen, fixed empty table styling, started filter function
- [x] [Read]( https://eloquentjavascript.net/ ) - Chapter 11

Saturday, July 29

- [x] Russell events page
- [ ] [Read]( https://eloquentjavascript.net/ )

**Comment by Bookcliff** [comment]
# Week of August 01:

## Goal: Six focused hours per day

Monday August 01:

- [x] Data science course (4 modules)

Tuesday, August 02:

- [x] Russell Events page (error handling)

Wednesday, August 03:

- [x] GoGo Pool Liquid Staking research (ANKR)

Thursday, August 04:

- [x] GoGo Pool Liquid Staking research (ANKR)

Friday, August 05:

- [x] GoGo Pool Liquid Staking research (ANKR)

Saturday, August 07:

- [ ] Russell Events Page
- [ ] [Read](https://eloquentjavascript.net/)

**Comment by Bookcliff** [comment]
# Week of August 07

Monday, August 08:

- [x] Data science course (2 modules)

Tuesday, August 09:

- [x] Data science course (2 modules)

Wednesday, August 10:

- [x] Data science course (3 modules)

Thursday, August 11:

- [x] Data science course (1 module)

Friday, August 12:

- [x] Data science course (2 modules)

Saturday, August 13:

**Comment by Bookcliff** [comment]
Monday, August 15:

- [x]  Data science course (6 modules)

Tuesday, August 16:

 - [x] Data science course (4 modules)

Wednesday, August 17:

- [x] Data science course (4 modules)

Thursday, August 18:

- [x] Data science course (3 modules)

Friday, August 19:

- [x] Data science course (7 modules)

Saturday, August 20:

- [x] Data science course (3 modules)

**Comment by Bookcliff** [comment]
August 21 - October 16
- [x] Completed data science course
- [x] Completed Twitter API project for GGP
- [x] Worked on GGP issues (e.g. fixed some bugs, hydration errors, added Crisp feature)
- [x] Worked on Events API page for ABG
- [x] Worked on Leads API page for ABG
- [x] Worked on Merch Runescape API with Russell (paired-programming)

**Comment by Bookcliff** [comment]
# Week of October 17

Monday, October 17

- [x] Read first 6 chapters of Cracking the Code Interview Guide
- [x] Reviewed DOM section of roadmap (https://dom.spec.whatwg.org/; https://www.youtube.com/watch?v=7Tok22qxPzQ; console.dir(document); etc.)

Tuesday, October 18

- [x] Version control systems (git, github)
- [x] Web security
- [x] package managers (yarn & npm)
- [x] CSS Architecture (BEM, OOCSS, SMACSS)
- [x] CSS Preprocessers (Sass, LESS, etc.)

Wednesday, October 19

- [x] Read [Webpack documentation](https://webpack.js.org/concepts/)
- [x] Read [Vite documentation](https://vitejs.dev/guide/)
- [x] Read [Parcel documentation](https://parceljs.org/docs/)
- [x] NPM scripts
- [x] Read about [ESLint](https://eslint.org/docs/latest/)
- [x] Read about [Prettier](https://prettier.io/docs/en/index.html)
- [x] Read [Less Docs](https://lesscss.org/)
- [x] Module Bundlers

Thursday, October 20

- [x] Module Bundlers

Friday, October 21

- [x] Reviewed JS frameworks
- [x] Read brief [overview of JS concepts](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Language_Overview#objects)
- [x] Re-read [React documentation](https://reactjs.org/docs/getting-started.html)
- [x] CSS - [styled components](https://github.com/Bookcliff/styled-components-test-project), CSS modules
- [x] CSS Frameworks (bootstrap, bulma, chakra ui, tailwind)

**Comment by Bookcliff** [comment]
# Week of October 24

Monday, October 24

- [x] Update current state of validator node's section of validator guide (GGP)
- [x] Read about (the graph)[https://thegraph.com/docs/en/]

Tuesday, October 25

- [x] Finished reading the graph documentation
- [x] Read (apollo docs)[https://www.apollographql.com/docs/]
- [x] Reviewed subgraph usage in arbor repos
- [x] Started building dynamic collateral display (https://arbor.garden)

Wednesday, October 26

- [x] Read about re-renders with Vanilla JS
- [x] Read adding state with Vanilla JS
- [x] Worked on collateral display component
- [x] GGP marketing editing

Thursday, October 27

- [x] GGP marketing editing
- [x] Read about promises and async/await functions
- [x] Read about [the DOM](https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Introduction)
- [x] Completed collateral display component
- [x] Read about call options

Friday, October 28

- [x] Read about call and put options
- [x] Set up https://github.com/alwaysbegrowing/company/issues/8

Sunday, October 30

- [x] Worked on https://github.com/alwaysbegrowing/company/issues/8 python set-up

**Comment by Bookcliff** [comment]
# Week of October 31

Monday, October 31

- [x] Worked on https://github.com/alwaysbegrowing/company/issues/8

Tuesday, November 01

- [x] Worked on adapting https://github.com/alwaysbegrowing/company/issues/8 to use AWS lambda function
- [x] GGP editing

Wednesday, November 02

- [x] Worked on https://github.com/alwaysbegrowing/company/issues/8 lambda function
- [x] Read about AWS, lambda functions, Docker, AWS CDK and components
- [x] GGP editing

Thursday, November 03

- [x] Worked on https://github.com/alwaysbegrowing/company/issues/8 lambda function
- [x] Read about CDK parameters
- [x] Set up AWS and vercel integration

Friday, November 04

- [x] Finished https://github.com/alwaysbegrowing/company/issues/8 lambda function

Saturday, November 05

- [x] Started working on https://github.com/alwaysbegrowing/company/issues/10

**Comment by Bookcliff** [comment]
# Week of November 06

Monday, November 07

- [x] Worked on https://github.com/alwaysbegrowing/company/issues/10
- [x] Reviewed DeFiLlama docs
- [x] Set up code template
- [x] GGP editing

Tuesday, November 08

- [x] Worked on https://github.com/alwaysbegrowing/company/issues/10
- [x] Read about ERC-20, smart contracts, tokens
- [x] GGP editing

Wednesday, November 09

- [x] Worked on https://github.com/alwaysbegrowing/company/issues/10
- [x] Read about ABIs, array.map
- [x] Read about MEV, front running

Thursday, November 10

- [x] Fixed events page rate limit issue
- [x] Read about blockchain lending protocols
- [x] Worked on events page ENS issue

**Comment by Bookcliff** [comment]
# Week of November 14

Monday, November 14

- [x] GGP editing
- [x] Finished adding networks to events page
- [x] Worked on adding ENS for events page
- [x] [Event loops](https://www.youtube.com/watch?v=8aGhZQkoFbQ)
- [x] [Asynchronous JavaScript](https://www.youtube.com/watch?v=rivBfgaEyWQ)
- [x] [Async/Await, Promises, Callbacks](https://www.youtube.com/watch?v=JRNToFh3hxU)
- [x] [More async/await  & callbacks](https://www.youtube.com/watch?v=_8gHHBlbziw)

Tuesday, November 15

- [x] GGP editing
- [x] Finished Tailwind test project
- [x] Research risk assessment protocols
- [x] Re-read [How Does the Internet Work](https://web.stanford.edu/class/msande91si/www-spr04/readings/week1/InternetWhitepaper.htm)

Wednesday, November 16

- [x] GGP editing
- [x] Read cracking the coding interview

Thursday, November 17

- [x] GGP and Arbor editing
- [x] Solv's intent to repay structure (ethSign)
- [x] Reviewed ethsign and openlaw
- [x] POAP
- [x] Data structures (https://www.geeksforgeeks.org/data-structures/?ref=lbp; https://www.javatpoint.com/data-structure-introduction): arrays, linked lists, stacks, queues, trees, tries, graphs, hash tables

Friday, November 18

- [x] Arbor editing
- [x] Gnosis safe (created Görli testnet)
- [x] Read Gnosis docs
- [x] POAP art
- [x] Arrays, linked lists, stack, queues, hashes

**Comment by Bookcliff** [comment]
# Week of November 21

Monday, November 21

- [x] Data structures: Hashing (open addressing), binary trees
- [x] Open & Past issuances component (Arbor)

Tuesday, November 22

- [x] Open & Past issuances component
- [x] Lighthouse optimization (arbor.finance; app.arbor.finance)
- [x] binary search

Wednesday, November 23

- [x] Arbor bug fix (https://github.com/alwaysbegrowing/arbor-frontend/issues/21)
- [x] POAP issuance request
- [x] https://github.com/alwaysbegrowing/arbor-frontend/pull/26
- [x] https://github.com/alwaysbegrowing/arbor-frontend/pull/28

Thursday, November 24

- [x] THANKSGIVING

Friday, November 25

- [x] Binary trees

**Comment by Bookcliff** [comment]
# Week of November 28

Monday, November 28 

- [x] GGP Editing
- [x] Fix https://github.com/alwaysbegrowing/arbor-frontend/pull/27
- [x] Binary Search Trees
- [x] Graph data structures ([lectures 10-15](https://www.youtube.com/watch?v=KyordYB3BOs&list=PLOtl7M3yp-DX6ic0HGT0PUX_wiNmkWkXx&index=12))
- [x] Breadth first search, depth first search
- [x] [Minimum spanning trees](https://www.youtube.com/watch?v=tKwnms5iRBU&index=16&list=PLUl4u3cNGP6317WaSNfmCvGym2ucw3oGp)

Tuesday, November 29

- [x] Review orderbook code
- [x] Fix https://github.com/alwaysbegrowing/arbor-frontend/pull/27
- [x] Read [0x docs](https://docs.0x.org/introduction/welcome)
- [x] Work on Arbor orderbook

Wednesday, November 30

- [x] https://github.com/alwaysbegrowing/arbor-frontend/pull/32
- [x] Fix bond documentation
- [x] Gas fees
- [x] [Orderbook](https://github.com/alwaysbegrowing/arbor-frontend/pull/35)
- [x] POAP image

Thursday, December 01

- [x] https://github.com/alwaysbegrowing/arbor-frontend/pull/36
- [x] https://github.com/alwaysbegrowing/arbor-frontend/pull/34
- [x] https://github.com/alwaysbegrowing/arbor-frontend/pull/33
- [x] https://github.com/alwaysbegrowing/arbor-frontend/pull/35

Friday, December 02

-  [x] https://github.com/alwaysbegrowing/arbor-frontend/pull/35

Saturday, December 03

- [x] https://github.com/alwaysbegrowing/arbor-frontend/pull/45

Sunday, December 04

- [x] https://github.com/alwaysbegrowing/arbor-frontend/pull/46

**Comment by Bookcliff** [comment]
# Week of December 05

Monday, December 05

- [x] Finished https://github.com/alwaysbegrowing/arbor-frontend/pull/46
- [x] https://github.com/alwaysbegrowing/arbor-frontend/pull/45
- [x] https://github.com/alwaysbegrowing/arbor-frontend/pull/51
- [x] https://github.com/alwaysbegrowing/arbor-frontend/pull/50
- [x] Worked on https://github.com/alwaysbegrowing/arbor-frontend/pull/35

Tuesday, December 06

- [x] Worked on https://github.com/alwaysbegrowing/arbor-frontend/pull/35
- [x] https://github.com/alwaysbegrowing/arbor-frontend/pull/55

Wednesday, December 07

- [x] https://github.com/alwaysbegrowing/arbor-frontend/pull/61
- [ ] https://github.com/alwaysbegrowing/arbor-frontend/issues/62
- [x] Worked on https://github.com/alwaysbegrowing/arbor-frontend/pull/35
- [x] Arbor bug/component fixes

Thursday, December 08

- [x] Arbor bug/component fixes
- [x] Worked on https://github.com/alwaysbegrowing/arbor-frontend/pull/35

**Comment by Bookcliff** [comment]
# Week of December 11 - 18

- [x] Lots and lots of Arbor stuff

**Comment by Bookcliff** [comment]
# Week of December 19

Monday December 19
- [x] Fix [bond interest](https://github.com/alwaysbegrowing/arbor-frontend/pull/93)
- [ ] Look into Alchemy notifications (EPNS will likely not be what we need)
- [x] https://github.com/alwaysbegrowing/company/issues/17
- [ ] https://github.com/alwaysbegrowing/company/issues/12

Tuesday December 20

- [ ] https://github.com/alwaysbegrowing/company/issues/12
- [ ] Look into Alchemy notifications (EPNS will likely not be what we need)
